export type FeaturedInterview = {
  id: string;
  title: string;
  role: string;
  level: "Intern" | "Junior" | "Mid" | "Senior";
  type: "Technical" | "HR" | "Mixed";
  techstack: string[];
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  estimatedDuration: string;
  questionCount: number;
  coverImage: string;
  description: string;
  badge: "Featured" | "Trending" | "Popular" | "New";
};

export const featuredInterviews: FeaturedInterview[] = [
  { id: "frontend-core", title: "Frontend Foundations", role: "Frontend Developer", level: "Junior", type: "Technical", techstack: ["HTML", "CSS", "JavaScript"], difficulty: "Beginner", estimatedDuration: "20 min", questionCount: 10, coverImage: "/covers/adobe.png", description: "Sharpen the browser, layout, and JavaScript essentials hiring teams ask first.", badge: "Featured" },
  { id: "backend-api", title: "Backend API Builder", role: "Backend Developer", level: "Mid", type: "Technical", techstack: ["Node.js", "REST APIs", "PostgreSQL"], difficulty: "Intermediate", estimatedDuration: "30 min", questionCount: 12, coverImage: "/covers/amazon.png", description: "Practice practical API design, data modeling, and service reliability questions.", badge: "Popular" },
  { id: "full-stack", title: "Full Stack Product", role: "Full Stack Developer", level: "Mid", type: "Mixed", techstack: ["React", "Node.js", "MongoDB"], difficulty: "Intermediate", estimatedDuration: "30 min", questionCount: 12, coverImage: "/covers/facebook.png", description: "A balanced product-engineering interview across client, server, and delivery.", badge: "Trending" },
  { id: "react", title: "React Specialist", role: "React Developer", level: "Mid", type: "Technical", techstack: ["React", "TypeScript", "Redux"], difficulty: "Intermediate", estimatedDuration: "25 min", questionCount: 10, coverImage: "/covers/pinterest.png", description: "Explore component architecture, state management, performance, and testing.", badge: "Featured" },
  { id: "nextjs", title: "Next.js Production", role: "Next.js Developer", level: "Mid", type: "Technical", techstack: ["Next.js", "React", "TypeScript"], difficulty: "Intermediate", estimatedDuration: "30 min", questionCount: 12, coverImage: "/covers/tiktok.png", description: "Get ready for routing, rendering, caching, and modern Next.js application design.", badge: "New" },
  { id: "angular", title: "Angular Engineer", role: "Angular Developer", level: "Mid", type: "Technical", techstack: ["Angular", "TypeScript", "RxJS"], difficulty: "Intermediate", estimatedDuration: "25 min", questionCount: 10, coverImage: "/covers/yahoo.png", description: "Practice framework architecture, reactive programming, and enterprise frontends.", badge: "Popular" },
  { id: "vue", title: "Vue Craft", role: "Vue Developer", level: "Junior", type: "Technical", techstack: ["Vue", "JavaScript", "Pinia"], difficulty: "Beginner", estimatedDuration: "20 min", questionCount: 8, coverImage: "/covers/skype.png", description: "Build confidence with Vue composition, state, and component communication.", badge: "New" },
  { id: "java", title: "Java Core", role: "Java Developer", level: "Mid", type: "Technical", techstack: ["Java", "OOP", "Collections"], difficulty: "Intermediate", estimatedDuration: "30 min", questionCount: 12, coverImage: "/covers/reddit.png", description: "Review language fundamentals, object design, collections, and concurrency.", badge: "Featured" },
  { id: "spring", title: "Spring Boot Services", role: "Spring Boot Developer", level: "Mid", type: "Technical", techstack: ["Java", "Spring Boot", "Microservices"], difficulty: "Advanced", estimatedDuration: "35 min", questionCount: 14, coverImage: "/covers/hostinger.png", description: "Dive into production Spring services, security, data, and distributed systems.", badge: "Trending" },
  { id: "python", title: "Python Problem Solver", role: "Python Developer", level: "Junior", type: "Technical", techstack: ["Python", "OOP", "Algorithms"], difficulty: "Beginner", estimatedDuration: "20 min", questionCount: 10, coverImage: "/covers/quora.png", description: "Strengthen Python fluency, clean code instincts, and everyday problem solving.", badge: "Popular" },
  { id: "node", title: "Node.js Services", role: "Node.js Developer", level: "Mid", type: "Technical", techstack: ["Node.js", "Express", "Redis"], difficulty: "Intermediate", estimatedDuration: "30 min", questionCount: 12, coverImage: "/covers/spotify.png", description: "Practice asynchronous systems, service patterns, and server-side performance.", badge: "Featured" },
  { id: "cpp", title: "Modern C++", role: "C++ Developer", level: "Senior", type: "Technical", techstack: ["C++", "STL", "Memory Management"], difficulty: "Advanced", estimatedDuration: "35 min", questionCount: 14, coverImage: "/covers/tiktok.png", description: "A demanding technical session on memory, performance, and modern C++ design.", badge: "New" },
  { id: "dsa", title: "DSA Sprint", role: "Software Engineer", level: "Mid", type: "Technical", techstack: ["Data Structures", "Algorithms", "Complexity"], difficulty: "Advanced", estimatedDuration: "35 min", questionCount: 14, coverImage: "/covers/telegram.png", description: "Train for core data structures, algorithm choices, and complexity trade-offs.", badge: "Trending" },
  { id: "operating-systems", title: "Operating Systems", role: "Systems Engineer", level: "Mid", type: "Technical", techstack: ["Operating Systems", "Linux", "Concurrency"], difficulty: "Advanced", estimatedDuration: "30 min", questionCount: 12, coverImage: "/covers/adobe.png", description: "Test your understanding of processes, memory, scheduling, and synchronization.", badge: "Popular" },
  { id: "networks", title: "Computer Networks", role: "Network Engineer", level: "Mid", type: "Technical", techstack: ["TCP/IP", "HTTP", "DNS"], difficulty: "Intermediate", estimatedDuration: "25 min", questionCount: 10, coverImage: "/covers/amazon.png", description: "Refresh the protocols and troubleshooting thinking behind modern networks.", badge: "Featured" },
  { id: "dbms", title: "DBMS & SQL", role: "Database Developer", level: "Mid", type: "Technical", techstack: ["SQL", "PostgreSQL", "Database Design"], difficulty: "Intermediate", estimatedDuration: "25 min", questionCount: 10, coverImage: "/covers/facebook.png", description: "Prepare for schemas, joins, transactions, indexes, and query optimization.", badge: "Popular" },
  { id: "machine-learning", title: "Machine Learning", role: "Machine Learning Engineer", level: "Mid", type: "Technical", techstack: ["Python", "Scikit-learn", "Statistics"], difficulty: "Advanced", estimatedDuration: "35 min", questionCount: 14, coverImage: "/covers/pinterest.png", description: "Practice model evaluation, feature engineering, and production ML fundamentals.", badge: "Trending" },
  { id: "ai-engineer", title: "AI Engineer", role: "AI Engineer", level: "Mid", type: "Technical", techstack: ["LLMs", "Python", "RAG"], difficulty: "Advanced", estimatedDuration: "35 min", questionCount: 14, coverImage: "/covers/yahoo.png", description: "Explore modern AI systems, prompt design, evaluation, and retrieval workflows.", badge: "New" },
  { id: "cloud", title: "Cloud Architecture", role: "Cloud Engineer", level: "Mid", type: "Technical", techstack: ["AWS", "Docker", "Kubernetes"], difficulty: "Advanced", estimatedDuration: "35 min", questionCount: 14, coverImage: "/covers/skype.png", description: "Discuss resilient cloud systems, containers, scaling, and operational trade-offs.", badge: "Featured" },
  { id: "devops", title: "DevOps Delivery", role: "DevOps Engineer", level: "Mid", type: "Technical", techstack: ["Docker", "Kubernetes", "CI/CD"], difficulty: "Advanced", estimatedDuration: "30 min", questionCount: 12, coverImage: "/covers/reddit.png", description: "Practice automation, observability, deployment, and infrastructure reliability.", badge: "Trending" },
  { id: "cybersecurity", title: "Cyber Security", role: "Cyber Security Analyst", level: "Mid", type: "Technical", techstack: ["Security", "Networking", "OWASP"], difficulty: "Advanced", estimatedDuration: "30 min", questionCount: 12, coverImage: "/covers/hostinger.png", description: "Prepare for secure design, threat analysis, web security, and incident response.", badge: "Popular" },
  { id: "hr", title: "HR Confidence", role: "Software Engineer", level: "Junior", type: "HR", techstack: ["Career Story", "Motivation", "Goals"], difficulty: "Beginner", estimatedDuration: "20 min", questionCount: 8, coverImage: "/covers/quora.png", description: "Build clear, confident answers for common recruiter and culture-fit questions.", badge: "Featured" },
  { id: "behavioral", title: "Behavioral Stories", role: "Software Engineer", level: "Mid", type: "Mixed", techstack: ["STAR Method", "Leadership", "Collaboration"], difficulty: "Intermediate", estimatedDuration: "25 min", questionCount: 10, coverImage: "/covers/spotify.png", description: "Practice concise, memorable stories about impact, ownership, and teamwork.", badge: "New" },
  { id: "communication", title: "Communication Skills", role: "Professional", level: "Junior", type: "HR", techstack: ["Communication", "Confidence", "Clarity"], difficulty: "Beginner", estimatedDuration: "20 min", questionCount: 8, coverImage: "/covers/telegram.png", description: "Develop a sharper interview presence, structured answers, and active listening.", badge: "Popular" },
];
